### ISSUE TITLE
super+q unresponsive on ubuntu 14.04.5 LTS

### ISSUE THREAD

**Issue by trappedinspacetime** [yamnikov-oleg/projektor#1]
Hi,
First of all thank you for developing such a launcher. Unfortunately Linux lacks a fast app launcher. I tried many of them, some craches suddenly, others not too fast in my computers specs. 
I installed your launcher but when I hit "super+q" keys no gui shows up. I also tried `projector -v` with no clues.
I hope I you help me.
Regardsi
Kenn

**Comment by yamnikov-oleg** [comment]
Hi, Kenn.

Thank you for the report, but I'm afraid, I don't have spare time to maintain projektor's development at the moment. Probably in few months, after I finish my diploma paper, I will get back you it.

As a temporary fix, I'd advice you to reinstall projektor with go 1.5. It could be broken because of updated pointer-passing rules of Cgo in go 1.6.

Also, you can run a foreground instance of projektor using command `projektor -inst`. If my key-binder fails, you might have more success binding that command to a hotkey using some other tool, e.g. `xbindkeys`.

Hope that helps. And I'm sorry for not being able to fix your issue.

Oleg.
